import {GeoPoint, Timestamp} from "firebase-admin/firestore";

import {currentSchemaVersion, seedDatasetVersion} from "../core/schema";

const createdAt = Timestamp.fromDate(new Date("2026-07-13T12:00:00.000Z"));
const eventStart = Timestamp.fromDate(new Date("2026-08-08T16:00:00.000Z"));
const eventEnd = Timestamp.fromDate(new Date("2026-08-08T18:00:00.000Z"));
const challengeStart = Timestamp.fromDate(new Date("2026-07-13T00:00:00.000Z"));
const challengeEnd = Timestamp.fromDate(new Date("2026-07-20T23:59:59.000Z"));

const audit = {
  createdAt,
  updatedAt: createdAt,
  schemaVersion: currentSchemaVersion,
};

export const seedDocuments = [
  {
    path: "app_config/mobile",
    data: {
      maintenanceMode: false,
      minimumSupportedBuild: 1,
      latestBuild: 1,
      defaultDiscoveryRadiusKm: 25,
      minimumAge: 13,
      maximumAge: 120,
      onboardingVersion: 1,
      supportedCountryCodes: ["IL"],
      termsVersion: "1.0",
      privacyVersion: "1.0",
      maxUploadBytes: {
        avatar: 10 * 1024 * 1024,
        post: 250 * 1024 * 1024,
        story: 150 * 1024 * 1024,
        marketplace: 15 * 1024 * 1024,
      },
      ...audit,
    },
  },
  {
    path: "feature_flags/ai_coach",
    data: {
      enabled: false,
      rolloutPercentage: 0,
      allowedPlatforms: ["android", "ios", "web"],
      minimumBuild: 1,
      description: "Controls the AI coach experience.",
      ...audit,
    },
  },
  {
    path: "feature_flags/marketplace",
    data: {
      enabled: true,
      rolloutPercentage: 100,
      allowedPlatforms: ["android", "ios", "web"],
      minimumBuild: 1,
      description: "Controls marketplace discovery and listings.",
      ...audit,
    },
  },
  ...[
    {
      id: "football",
      slug: "football",
      localizedNames: {en: "Football", ar: "كرة القدم", he: "כדורגל"},
      iconKey: "football",
      sortOrder: 10,
      supportedFeatures: ["places", "teams", "events", "challenges", "trainers"],
    },
    {
      id: "gym",
      slug: "gym",
      localizedNames: {en: "Gym", ar: "النادي الرياضي", he: "חדר כושר"},
      iconKey: "gym",
      sortOrder: 20,
      supportedFeatures: ["places", "groups", "events", "challenges", "trainers", "pricing"],
    },
    {
      id: "running",
      slug: "running",
      localizedNames: {en: "Running", ar: "الجري", he: "ריצה"},
      iconKey: "running",
      sortOrder: 30,
      supportedFeatures: ["routes", "groups", "events", "challenges", "leaderboards"],
    },
  ].map((sport) => ({
    path: `sports/${sport.id}`,
    data: {
      slug: sport.slug,
      localizedNames: sport.localizedNames,
      iconKey: sport.iconKey,
      isEnabled: true,
      sortOrder: sport.sortOrder,
      supportedFeatures: sport.supportedFeatures,
      ...audit,
    },
  })),
  {
    path: "usernames/demo_athlete",
    data: {uid: "demo-athlete", reservedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-athlete",
    data: {
      uid: "demo-athlete",
      username: "demo_athlete",
      usernameNormalized: "demo_athlete",
      displayName: "ReeMove Athlete",
      bio: "Training, meeting players, and moving every day.",
      role: "athlete",
      isVerified: false,
      verificationType: "none",
      favoriteSportIds: ["football", "gym", "running"],
      sportLevels: {football: "intermediate", gym: "advanced", running: "intermediate"},
      goals: ["find_training_partners", "stay_active", "improve_endurance"],
      location: new GeoPoint(32.7940, 34.9896),
      geohash: "svbcr",
      locality: "Haifa",
      administrativeArea: "Haifa District",
      countryCode: "IL",
      discoveryRadiusKm: 25,
      visibility: "public",
      followersCount: 0,
      followingCount: 1,
      postsCount: 1,
      onboardingCompleted: true,
      onboardingVersion: 1,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "users/demo-athlete/private/profile",
    data: {
      uid: "demo-athlete",
      email: "athlete@demo.reemove.app",
      emailNormalized: "athlete@demo.reemove.app",
      providerIds: ["password"],
      accountStatus: "active",
      lastSignInAt: createdAt,
      dateOfBirth: "2000-01-01",
      ageBand: "25_34",
      isMinor: false,
      onboardingVersion: 1,
      onboardingCompletedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/private/consents",
    data: {
      uid: "demo-athlete",
      termsVersion: "1.0",
      privacyVersion: "1.0",
      termsAcceptedAt: createdAt,
      privacyAcceptedAt: createdAt,
      minimumAgeConfirmedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/private/preferences",
    data: {
      uid: "demo-athlete",
      discovery: {
        radiusKm: 25,
        showNearbyPeople: true,
        recommendEvents: true,
        allowTrainerDiscovery: true,
        visibility: "public",
      },
      accessibility: {
        reduceMotion: false,
        highContrast: false,
        largeText: false,
        screenReaderOptimized: false,
      },
      notifications: {
        masterEnabled: false,
        activity: true,
        messages: true,
        events: true,
        challenges: true,
        productUpdates: false,
        permissionStatus: "notAsked",
      },
      locationPermission: "granted",
      exactLocation: {
        location: new GeoPoint(32.7940, 34.9896),
        geohash: "svbfs1r1n",
        locality: "Haifa",
        administrativeArea: "Haifa District",
        countryCode: "IL",
      },
      schemaVersion: currentSchemaVersion,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/private/onboarding",
    data: {
      uid: "demo-athlete",
      version: 1,
      currentStep: "review",
      dateOfBirth: "2000-01-01",
      avatarUrl: null,
      avatarStoragePath: null,
      favoriteSportIds: ["football", "gym", "running"],
      sportLevels: {football: "intermediate", gym: "advanced", running: "intermediate"},
      goals: ["stay_active", "find_training_partners", "improve_endurance"],
      location: {
        latitude: 32.7940,
        longitude: 34.9896,
        locality: "Haifa",
        administrativeArea: "Haifa District",
        countryCode: "IL",
      },
      locationPermission: "granted",
      discovery: {
        radiusKm: 25,
        showNearbyPeople: true,
        recommendEvents: true,
        allowTrainerDiscovery: true,
        visibility: "public",
      },
      accessibility: {
        reduceMotion: false,
        highContrast: false,
        largeText: false,
        screenReaderOptimized: false,
      },
      notifications: {
        masterEnabled: false,
        activity: true,
        messages: true,
        events: true,
        challenges: true,
        productUpdates: false,
        permissionStatus: "notAsked",
      },
      status: "completed",
      completedAt: createdAt,
      createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "usernames/demo_newcomer",
    data: {uid: "demo-newcomer", reservedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-newcomer",
    data: {
      uid: "demo-newcomer",
      username: "demo_newcomer",
      usernameNormalized: "demo_newcomer",
      displayName: "ReeMove Newcomer",
      bio: "",
      role: "athlete",
      isVerified: false,
      verificationType: "none",
      favoriteSportIds: [],
      sportLevels: {},
      goals: [],
      discoveryRadiusKm: 25,
      visibility: "public",
      followersCount: 0,
      followingCount: 0,
      postsCount: 0,
      onboardingCompleted: false,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "users/demo-newcomer/private/profile",
    data: {
      uid: "demo-newcomer",
      email: "newcomer@demo.reemove.app",
      emailNormalized: "newcomer@demo.reemove.app",
      providerIds: ["password"],
      accountStatus: "active",
      lastSignInAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-newcomer/private/consents",
    data: {
      uid: "demo-newcomer",
      termsVersion: "1.0",
      privacyVersion: "1.0",
      termsAcceptedAt: createdAt,
      privacyAcceptedAt: createdAt,
      minimumAgeConfirmedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "usernames/demo_runner",
    data: {uid: "demo-runner", reservedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-runner",
    data: {
      uid: "demo-runner",
      username: "demo_runner",
      usernameNormalized: "demo_runner",
      displayName: "Maya Runner",
      bio: "Easy miles, trail mornings, and community runs.",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
      role: "athlete",
      isVerified: true,
      verificationType: "athlete",
      favoriteSportIds: ["running", "gym"],
      sportLevels: {running: "advanced", gym: "intermediate"},
      goals: ["improve_endurance", "find_training_partners"],
      location: new GeoPoint(32.8191, 34.9569),
      geohash: "svbcw",
      locality: "Haifa",
      administrativeArea: "Haifa District",
      countryCode: "IL",
      discoveryRadiusKm: 25,
      visibility: "public",
      followersCount: 1,
      followingCount: 0,
      postsCount: 2,
      onboardingCompleted: true,
      onboardingVersion: 1,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "users/demo-runner/private/profile",
    data: {
      uid: "demo-runner",
      email: "runner@demo.reemove.app",
      emailNormalized: "runner@demo.reemove.app",
      providerIds: ["password"],
      accountStatus: "active",
      lastSignInAt: createdAt,
      dateOfBirth: "1998-04-12",
      ageBand: "25_34",
      isMinor: false,
      onboardingVersion: 1,
      onboardingCompletedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/following/demo-runner",
    data: {uid: "demo-runner", createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-runner/followers/demo-athlete",
    data: {uid: "demo-athlete", createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "posts/demo-run-finish",
    data: {
      authorId: "demo-runner",
      authorSnapshot: {
        id: "demo-runner",
        username: "demo_runner",
        displayName: "Maya Runner",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
        isVerified: true,
        verificationType: "athlete",
      },
      kind: "post",
      caption: "Sunrise tempo complete. Eight controlled kilometres and a calm finish. #running #haifa",
      media: [{
        id: "seed-run-image",
        storagePath: "seed/external/run.jpg",
        kind: "image",
        processingState: "ready",
        downloadUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=85",
        width: 1400,
        height: 933,
        contentType: "image/jpeg",
      }],
      hashtags: ["running", "haifa"],
      mentions: [],
      sportId: "running",
      locationLabel: "Haifa Promenade",
      visibility: "public",
      moderationState: "active",
      status: "published",
      allowComments: true,
      likeCount: 36,
      commentCount: 1,
      saveCount: 4,
      repostCount: 2,
      viewCount: 188,
      rankingScore: 92.5,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T11:20:00.000Z")),
      ...audit,
    },
  },
  {
    path: "posts/demo-training-carousel",
    data: {
      authorId: "demo-athlete",
      authorSnapshot: {
        id: "demo-athlete",
        username: "demo_athlete",
        displayName: "ReeMove Athlete",
        isVerified: false,
        verificationType: "none",
      },
      kind: "post",
      caption: "Strength day: clean reps, steady progress, and no skipped warm-up. #gym #progress",
      media: [
        {
          id: "seed-gym-1",
          storagePath: "seed/external/gym-1.jpg",
          kind: "image",
          processingState: "ready",
          downloadUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=85",
          width: 1400,
          height: 933,
          contentType: "image/jpeg",
        },
        {
          id: "seed-gym-2",
          storagePath: "seed/external/gym-2.jpg",
          kind: "image",
          processingState: "ready",
          downloadUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1400&q=85",
          width: 1400,
          height: 933,
          contentType: "image/jpeg",
        },
      ],
      hashtags: ["gym", "progress"],
      mentions: [],
      sportId: "gym",
      locationLabel: "Haifa Performance Gym",
      visibility: "public",
      moderationState: "active",
      status: "published",
      allowComments: true,
      likeCount: 18,
      commentCount: 0,
      saveCount: 3,
      repostCount: 1,
      viewCount: 104,
      rankingScore: 78.0,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T10:15:00.000Z")),
      ...audit,
    },
  },
  {
    path: "posts/demo-running-reel",
    data: {
      authorId: "demo-runner",
      authorSnapshot: {
        id: "demo-runner",
        username: "demo_runner",
        displayName: "Maya Runner",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
        isVerified: true,
        verificationType: "athlete",
      },
      kind: "reel",
      caption: "Quick feet before the main set. #runningdrills",
      media: [{
        id: "seed-reel-video",
        storagePath: "seed/external/bee.mp4",
        kind: "video",
        processingState: "ready",
        downloadUrl: "https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4",
        thumbnailUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=80",
        width: 720,
        height: 1280,
        durationMs: 7000,
        contentType: "video/mp4",
      }],
      hashtags: ["runningdrills"],
      mentions: [],
      sportId: "running",
      visibility: "public",
      moderationState: "active",
      status: "published",
      allowComments: true,
      likeCount: 61,
      commentCount: 0,
      saveCount: 11,
      repostCount: 5,
      viewCount: 430,
      rankingScore: 99.0,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T09:45:00.000Z")),
      ...audit,
    },
  },
  {
    path: "posts/demo-run-finish/comments/seed-comment",
    data: {
      postId: "demo-run-finish",
      authorId: "demo-athlete",
      authorSnapshot: {
        id: "demo-athlete",
        username: "demo_athlete",
        displayName: "ReeMove Athlete",
        isVerified: false,
        verificationType: "none",
      },
      text: "Strong finish. See you at the weekend run!",
      parentCommentId: null,
      likeCount: 2,
      replyCount: 0,
      moderationState: "active",
      createdAt: Timestamp.fromDate(new Date("2026-07-13T11:32:00.000Z")),
      updatedAt: Timestamp.fromDate(new Date("2026-07-13T11:32:00.000Z")),
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "feed_entries/demo-athlete--demo-run-finish",
    data: {
      recipientId: "demo-athlete",
      postId: "demo-run-finish",
      authorId: "demo-runner",
      source: "following",
      rankingScore: 92.5,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T11:20:00.000Z")),
      createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "feed_entries/demo-athlete--demo-running-reel",
    data: {
      recipientId: "demo-athlete",
      postId: "demo-running-reel",
      authorId: "demo-runner",
      source: "following",
      rankingScore: 99.0,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T09:45:00.000Z")),
      createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "content_reactions/demo-athlete--demo-run-finish",
    data: {
      uid: "demo-athlete",
      postId: "demo-run-finish",
      liked: true,
      saved: false,
      reposted: false,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "stories/demo-runner-morning",
    data: {
      authorId: "demo-runner",
      authorSnapshot: {
        id: "demo-runner",
        username: "demo_runner",
        displayName: "Maya Runner",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
        isVerified: true,
        verificationType: "athlete",
      },
      media: {
        id: "seed-story-image",
        storagePath: "seed/external/story.jpg",
        kind: "image",
        processingState: "ready",
        downloadUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=900&q=85",
        width: 900,
        height: 1600,
        contentType: "image/jpeg",
      },
      caption: "First light, first kilometres.",
      sportId: "running",
      visibility: "public",
      moderationState: "active",
      viewCount: 12,
      createdAt: Timestamp.fromDate(new Date("2026-07-13T11:00:00.000Z")),
      updatedAt: Timestamp.fromDate(new Date("2026-07-13T11:00:00.000Z")),
      expiresAt: Timestamp.fromDate(new Date("2026-07-14T11:00:00.000Z")),
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "places/haifa-performance-gym",
    data: {
      name: "Haifa Performance Gym",
      description: "Strength, functional training, and coached sessions.",
      type: "gym",
      sportIds: ["gym"],
      location: new GeoPoint(32.7940, 34.9896),
      geohash: "svbcr",
      addressLine: "10 Sports Avenue",
      city: "Haifa",
      countryCode: "IL",
      media: [],
      pricingText: "Day passes and monthly plans available",
      rating: 4.8,
      reviewCount: 128,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "places/tamra-community-pitch",
    data: {
      name: "Tamra Community Pitch",
      description: "Outdoor football pitch for community matches.",
      type: "pitch",
      sportIds: ["football"],
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      addressLine: "Community Sports Complex",
      city: "Tamra",
      countryCode: "IL",
      media: [],
      rating: 4.5,
      reviewCount: 54,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "places/haifa-coastal-running-track",
    data: {
      name: "Haifa Coastal Running Track",
      description: "A flat seafront route suited to easy runs and intervals.",
      type: "track",
      sportIds: ["running"],
      location: new GeoPoint(32.8191, 34.9569),
      geohash: "svbcw",
      addressLine: "Haifa Promenade",
      city: "Haifa",
      countryCode: "IL",
      media: [],
      rating: 4.7,
      reviewCount: 203,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "events/community-football-august",
    data: {
      ownerId: "demo-athlete",
      sportId: "football",
      type: "match",
      title: "Saturday Community Football",
      description: "Friendly seven-a-side match. Bring water and arrive 15 minutes early.",
      startAt: eventStart,
      endAt: eventEnd,
      timezone: "Asia/Jerusalem",
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      locality: "Tamra",
      countryCode: "IL",
      placeId: "tamra-community-pitch",
      capacity: 14,
      attendeeCount: 1,
      minimumLevel: "beginner",
      maximumLevel: "advanced",
      price: {amountMinor: 0, currency: "ILS"},
      visibility: "public",
      status: "published",
      moderationState: "active",
      media: [],
      ...audit,
    },
  },
  {
    path: "challenges/weekly-5k-consistency",
    data: {
      creatorId: "system",
      sportId: "running",
      title: "Weekly 5K Consistency",
      description: "Complete a total of five kilometres during the week.",
      source: "official",
      status: "active",
      startsAt: challengeStart,
      endsAt: challengeEnd,
      rules: [{metric: "distance", target: 5, unit: "km", verificationMethod: "activity"}],
      media: [],
      participantCount: 0,
      badgeId: "weekly-runner",
      rewardIds: [],
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "marketplace_listings/demo-adjustable-bench",
    data: {
      sellerId: "demo-athlete",
      seller: {
        uid: "demo-athlete",
        username: "demo_athlete",
        displayName: "ReeMove Athlete",
        isVerified: false,
      },
      title: "Adjustable Training Bench",
      description: "Well-maintained adjustable bench suitable for a home gym.",
      categoryId: "strength-equipment",
      sportId: "gym",
      condition: "good",
      price: {amountMinor: 55000, currency: "ILS"},
      media: [],
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      locality: "Tamra",
      countryCode: "IL",
      deliveryOptions: ["pickup"],
      status: "active",
      favoriteCount: 0,
      viewCount: 0,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: `data_migrations/${seedDatasetVersion}`,
    data: {
      version: seedDatasetVersion,
      type: "seed",
      status: "applied",
      appliedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
] as const;
