import {GeoPoint, Timestamp} from "firebase-admin/firestore";

import {currentSchemaVersion, seedDatasetVersion} from "../core/schema";

const createdAt = Timestamp.fromDate(new Date("2026-07-13T12:00:00.000Z"));
const eventStart = Timestamp.fromDate(new Date("2026-08-08T16:00:00.000Z"));
const eventEnd = Timestamp.fromDate(new Date("2026-08-08T18:00:00.000Z"));
const challengeStart = Timestamp.fromDate(new Date("2026-07-13T00:00:00.000Z"));
const challengeEnd = Timestamp.fromDate(new Date("2026-07-20T23:59:59.000Z"));

const audit = {
  createdAt,
  updatedAt: createdAt,
  schemaVersion: currentSchemaVersion,
};

export const seedDocuments = [
  {
    path: "app_config/mobile",
    data: {
      maintenanceMode: false,
      minimumSupportedBuild: 1,
      latestBuild: 1,
      defaultDiscoveryRadiusKm: 25,
      supportedCountryCodes: ["IL"],
      termsVersion: "1.0",
      privacyVersion: "1.0",
      maxUploadBytes: {
        avatar: 10 * 1024 * 1024,
        post: 250 * 1024 * 1024,
        story: 150 * 1024 * 1024,
        marketplace: 15 * 1024 * 1024,
      },
      ...audit,
    },
  },
  {
    path: "feature_flags/ai_coach",
    data: {
      enabled: false,
      rolloutPercentage: 0,
      allowedPlatforms: ["android", "ios", "web"],
      minimumBuild: 1,
      description: "Controls the AI coach experience.",
      ...audit,
    },
  },
  {
    path: "feature_flags/marketplace",
    data: {
      enabled: true,
      rolloutPercentage: 100,
      allowedPlatforms: ["android", "ios", "web"],
      minimumBuild: 1,
      description: "Controls marketplace discovery and listings.",
      ...audit,
    },
  },
  ...[
    {
      id: "football",
      slug: "football",
      localizedNames: {en: "Football", ar: "كرة القدم", he: "כדורגל"},
      iconKey: "football",
      sortOrder: 10,
      supportedFeatures: ["places", "teams", "events", "challenges", "trainers"],
    },
    {
      id: "gym",
      slug: "gym",
      localizedNames: {en: "Gym", ar: "النادي الرياضي", he: "חדר כושר"},
      iconKey: "gym",
      sortOrder: 20,
      supportedFeatures: ["places", "groups", "events", "challenges", "trainers", "pricing"],
    },
    {
      id: "running",
      slug: "running",
      localizedNames: {en: "Running", ar: "الجري", he: "ריצה"},
      iconKey: "running",
      sortOrder: 30,
      supportedFeatures: ["routes", "groups", "events", "challenges", "leaderboards"],
    },
  ].map((sport) => ({
    path: `sports/${sport.id}`,
    data: {
      slug: sport.slug,
      localizedNames: sport.localizedNames,
      iconKey: sport.iconKey,
      isEnabled: true,
      sortOrder: sport.sortOrder,
      supportedFeatures: sport.supportedFeatures,
      ...audit,
    },
  })),
  {
    path: "usernames/demo_athlete",
    data: {uid: "demo-athlete", reservedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-athlete",
    data: {
      uid: "demo-athlete",
      username: "demo_athlete",
      usernameNormalized: "demo_athlete",
      displayName: "ReeMove Athlete",
      bio: "Training, meeting players, and moving every day.",
      role: "athlete",
      isVerified: false,
      verificationType: "none",
      favoriteSportIds: ["football", "gym", "running"],
      sportLevels: {football: "intermediate", gym: "advanced", running: "intermediate"},
      goals: ["community", "consistency", "performance"],
      location: new GeoPoint(32.7940, 34.9896),
      geohash: "svbcr",
      locality: "Haifa",
      administrativeArea: "Haifa District",
      countryCode: "IL",
      discoveryRadiusKm: 25,
      visibility: "public",
      followersCount: 0,
      followingCount: 0,
      postsCount: 0,
      onboardingCompleted: true,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "users/demo-athlete/private/profile",
    data: {
      uid: "demo-athlete",
      email: "athlete@demo.reemove.app",
      emailNormalized: "athlete@demo.reemove.app",
      providerIds: ["password"],
      accountStatus: "active",
      lastSignInAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/private/consents",
    data: {
      uid: "demo-athlete",
      termsVersion: "1.0",
      privacyVersion: "1.0",
      termsAcceptedAt: createdAt,
      privacyAcceptedAt: createdAt,
      minimumAgeConfirmedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "places/haifa-performance-gym",
    data: {
      name: "Haifa Performance Gym",
      description: "Strength, functional training, and coached sessions.",
      type: "gym",
      sportIds: ["gym"],
      location: new GeoPoint(32.7940, 34.9896),
      geohash: "svbcr",
      addressLine: "10 Sports Avenue",
      city: "Haifa",
      countryCode: "IL",
      media: [],
      pricingText: "Day passes and monthly plans available",
      rating: 4.8,
      reviewCount: 128,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "places/tamra-community-pitch",
    data: {
      name: "Tamra Community Pitch",
      description: "Outdoor football pitch for community matches.",
      type: "pitch",
      sportIds: ["football"],
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      addressLine: "Community Sports Complex",
      city: "Tamra",
      countryCode: "IL",
      media: [],
      rating: 4.5,
      reviewCount: 54,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "places/haifa-coastal-running-track",
    data: {
      name: "Haifa Coastal Running Track",
      description: "A flat seafront route suited to easy runs and intervals.",
      type: "track",
      sportIds: ["running"],
      location: new GeoPoint(32.8191, 34.9569),
      geohash: "svbcw",
      addressLine: "Haifa Promenade",
      city: "Haifa",
      countryCode: "IL",
      media: [],
      rating: 4.7,
      reviewCount: 203,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "events/community-football-august",
    data: {
      ownerId: "demo-athlete",
      sportId: "football",
      type: "match",
      title: "Saturday Community Football",
      description: "Friendly seven-a-side match. Bring water and arrive 15 minutes early.",
      startAt: eventStart,
      endAt: eventEnd,
      timezone: "Asia/Jerusalem",
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      locality: "Tamra",
      countryCode: "IL",
      placeId: "tamra-community-pitch",
      capacity: 14,
      attendeeCount: 1,
      minimumLevel: "beginner",
      maximumLevel: "advanced",
      price: {amountMinor: 0, currency: "ILS"},
      visibility: "public",
      status: "published",
      moderationState: "active",
      media: [],
      ...audit,
    },
  },
  {
    path: "challenges/weekly-5k-consistency",
    data: {
      creatorId: "system",
      sportId: "running",
      title: "Weekly 5K Consistency",
      description: "Complete a total of five kilometres during the week.",
      source: "official",
      status: "active",
      startsAt: challengeStart,
      endsAt: challengeEnd,
      rules: [{metric: "distance", target: 5, unit: "km", verificationMethod: "activity"}],
      media: [],
      participantCount: 0,
      badgeId: "weekly-runner",
      rewardIds: [],
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "marketplace_listings/demo-adjustable-bench",
    data: {
      sellerId: "demo-athlete",
      seller: {
        uid: "demo-athlete",
        username: "demo_athlete",
        displayName: "ReeMove Athlete",
        isVerified: false,
      },
      title: "Adjustable Training Bench",
      description: "Well-maintained adjustable bench suitable for a home gym.",
      categoryId: "strength-equipment",
      sportId: "gym",
      condition: "good",
      price: {amountMinor: 55000, currency: "ILS"},
      media: [],
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      locality: "Tamra",
      countryCode: "IL",
      deliveryOptions: ["pickup"],
      status: "active",
      favoriteCount: 0,
      viewCount: 0,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: `data_migrations/${seedDatasetVersion}`,
    data: {
      version: seedDatasetVersion,
      type: "seed",
      status: "applied",
      appliedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
] as const;
