import {GeoPoint, Timestamp} from "firebase-admin/firestore";
import {geohashForLocation} from "geofire-common";

import {currentSchemaVersion, seedDatasetVersion} from "../core/schema";
import {directConversationId} from "../messaging/messagingPolicy";

const createdAt = Timestamp.fromDate(new Date("2026-07-13T12:00:00.000Z"));
const eventStart = Timestamp.fromDate(new Date("2026-08-08T16:00:00.000Z"));
const eventEnd = Timestamp.fromDate(new Date("2026-08-08T18:00:00.000Z"));
const challengeStart = Timestamp.fromDate(new Date("2026-07-13T00:00:00.000Z"));
const challengeEnd = Timestamp.fromDate(new Date("2026-07-20T23:59:59.000Z"));

const directSeedConversationId = directConversationId("demo-athlete", "demo-runner");
const groupSeedConversationId = "group_demo_weekend_training";

const athleteMessageSnapshot = {id: "demo-athlete", username: "demo_athlete", displayName: "ReeMove Athlete", isVerified: false};
const runnerMessageSnapshot = {id: "demo-runner", username: "maya_runner", displayName: "Maya Runner", isVerified: true};
const newcomerMessageSnapshot = {id: "demo-newcomer", username: "demo_newcomer", displayName: "ReeMove Newcomer", isVerified: false};

const audit = {
  createdAt,
  updatedAt: createdAt,
  schemaVersion: currentSchemaVersion,
};

export const seedDocuments = [
  {
    path: "app_config/mobile",
    data: {
      maintenanceMode: false,
      minimumSupportedBuild: 1,
      latestBuild: 1,
      defaultDiscoveryRadiusKm: 25,
      minimumAge: 13,
      maximumAge: 120,
      onboardingVersion: 1,
      supportedCountryCodes: ["IL"],
      termsVersion: "1.0",
      privacyVersion: "1.0",
      maxUploadBytes: {
        avatar: 10 * 1024 * 1024,
        post: 250 * 1024 * 1024,
        story: 150 * 1024 * 1024,
        marketplace: 15 * 1024 * 1024,
      },
      ...audit,
    },
  },
  {
    path: "feature_flags/ai_coach",
    data: {
      enabled: true,
      rolloutPercentage: 0,
      allowedPlatforms: ["android", "ios", "web"],
      minimumBuild: 1,
      description: "Controls the AI coach experience.",
      ...audit,
    },
  },
  {
    path: "feature_flags/marketplace",
    data: {
      enabled: true,
      rolloutPercentage: 100,
      allowedPlatforms: ["android", "ios", "web"],
      minimumBuild: 1,
      description: "Controls marketplace discovery and listings.",
      ...audit,
    },
  },
  ...[
    {
      id: "football",
      slug: "football",
      localizedNames: {en: "Football", ar: "كرة القدم", he: "כדורגל"},
      iconKey: "football",
      sortOrder: 10,
      supportedFeatures: ["places", "teams", "events", "challenges", "trainers"],
    },
    {
      id: "gym",
      slug: "gym",
      localizedNames: {en: "Gym", ar: "النادي الرياضي", he: "חדר כושר"},
      iconKey: "gym",
      sortOrder: 20,
      supportedFeatures: ["places", "groups", "events", "challenges", "trainers", "pricing"],
    },
    {
      id: "running",
      slug: "running",
      localizedNames: {en: "Running", ar: "الجري", he: "ריצה"},
      iconKey: "running",
      sortOrder: 30,
      supportedFeatures: ["routes", "groups", "events", "challenges", "leaderboards"],
    },
  ].map((sport) => ({
    path: `sports/${sport.id}`,
    data: {
      slug: sport.slug,
      localizedNames: sport.localizedNames,
      iconKey: sport.iconKey,
      isEnabled: true,
      sortOrder: sport.sortOrder,
      supportedFeatures: sport.supportedFeatures,
      ...audit,
    },
  })),
  {
    path: "usernames/demo_athlete",
    data: {uid: "demo-athlete", reservedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-athlete",
    data: {
      uid: "demo-athlete",
      username: "demo_athlete",
      usernameNormalized: "demo_athlete",
      displayName: "ReeMove Athlete",
      bio: "Training, meeting players, and moving every day.",
      coverUrl: "https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1600&q=85",
      websiteUrl: "https://reemove.app/u/demo_athlete",
      primarySportId: "football",
      role: "athlete",
      isVerified: false,
      verificationType: "none",
      professionalDetails: {
        headline: "Community football and strength athlete",
        organization: null,
        positionOrCategory: "Midfielder",
        yearsExperience: 6,
        specialties: ["football", "strength"],
        acceptingClients: false,
      },
      favoriteSportIds: ["football", "gym", "running"],
      sportLevels: {football: "intermediate", gym: "advanced", running: "intermediate"},
      goals: ["find_training_partners", "stay_active", "improve_endurance"],
      location: new GeoPoint(32.7940, 34.9896),
      geohash: "svbcr",
      locality: "Haifa",
      administrativeArea: "Haifa District",
      countryCode: "IL",
      discoveryRadiusKm: 25,
      visibility: "public",
      followApprovalPolicy: "approvalRequired",
      followersCount: 0,
      followingCount: 1,
      postsCount: 1,
      reelsCount: 0,
      onboardingCompleted: true,
      onboardingVersion: 1,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "users/demo-athlete/private/profile",
    data: {
      uid: "demo-athlete",
      email: "athlete@demo.reemove.app",
      emailNormalized: "athlete@demo.reemove.app",
      providerIds: ["password"],
      accountStatus: "active",
      lastSignInAt: createdAt,
      dateOfBirth: "2000-01-01",
      ageBand: "25_34",
      isMinor: false,
      onboardingVersion: 1,
      onboardingCompletedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/private/consents",
    data: {
      uid: "demo-athlete",
      termsVersion: "1.0",
      privacyVersion: "1.0",
      termsAcceptedAt: createdAt,
      privacyAcceptedAt: createdAt,
      minimumAgeConfirmedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/private/preferences",
    data: {
      uid: "demo-athlete",
      discovery: {
        radiusKm: 25,
        showNearbyPeople: true,
        recommendEvents: true,
        allowTrainerDiscovery: true,
        visibility: "public",
      },
      accessibility: {
        reduceMotion: false,
        highContrast: false,
        largeText: false,
        screenReaderOptimized: false,
      },
      notifications: {
        masterEnabled: true,
        showPreviews: true,
        activity: true,
        messages: true,
        events: true,
        challenges: true,
        marketplace: true,
        system: true,
        productUpdates: false,
        permissionStatus: "authorized",
        quietHours: {
          enabled: true,
          startMinutes: 1320,
          endMinutes: 420,
          utcOffsetMinutes: 180,
        },
      },
      locationPermission: "granted",
      exactLocation: {
        location: new GeoPoint(32.7940, 34.9896),
        geohash: "svbfs1r1n",
        locality: "Haifa",
        administrativeArea: "Haifa District",
        countryCode: "IL",
      },
      schemaVersion: currentSchemaVersion,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/private/onboarding",
    data: {
      uid: "demo-athlete",
      version: 1,
      currentStep: "review",
      dateOfBirth: "2000-01-01",
      avatarUrl: null,
      avatarStoragePath: null,
      favoriteSportIds: ["football", "gym", "running"],
      sportLevels: {football: "intermediate", gym: "advanced", running: "intermediate"},
      goals: ["stay_active", "find_training_partners", "improve_endurance"],
      location: {
        latitude: 32.7940,
        longitude: 34.9896,
        locality: "Haifa",
        administrativeArea: "Haifa District",
        countryCode: "IL",
      },
      locationPermission: "granted",
      discovery: {
        radiusKm: 25,
        showNearbyPeople: true,
        recommendEvents: true,
        allowTrainerDiscovery: true,
        visibility: "public",
      },
      accessibility: {
        reduceMotion: false,
        highContrast: false,
        largeText: false,
        screenReaderOptimized: false,
      },
      notifications: {
        masterEnabled: true,
        showPreviews: true,
        activity: true,
        messages: true,
        events: true,
        challenges: true,
        marketplace: true,
        system: true,
        productUpdates: false,
        permissionStatus: "authorized",
        quietHours: {
          enabled: false,
          startMinutes: 1320,
          endMinutes: 420,
          utcOffsetMinutes: 180,
        },
      },
      status: "completed",
      completedAt: createdAt,
      createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "usernames/demo_newcomer",
    data: {uid: "demo-newcomer", reservedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-newcomer",
    data: {
      uid: "demo-newcomer",
      username: "demo_newcomer",
      usernameNormalized: "demo_newcomer",
      displayName: "ReeMove Newcomer",
      bio: "",
      role: "athlete",
      isVerified: false,
      verificationType: "none",
      favoriteSportIds: [],
      sportLevels: {},
      goals: [],
      discoveryRadiusKm: 25,
      visibility: "public",
      followApprovalPolicy: "automatic",
      followersCount: 0,
      followingCount: 0,
      postsCount: 0,
      reelsCount: 0,
      onboardingCompleted: false,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "users/demo-newcomer/private/profile",
    data: {
      uid: "demo-newcomer",
      email: "newcomer@demo.reemove.app",
      emailNormalized: "newcomer@demo.reemove.app",
      providerIds: ["password"],
      accountStatus: "active",
      lastSignInAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-newcomer/private/consents",
    data: {
      uid: "demo-newcomer",
      termsVersion: "1.0",
      privacyVersion: "1.0",
      termsAcceptedAt: createdAt,
      privacyAcceptedAt: createdAt,
      minimumAgeConfirmedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "usernames/demo_runner",
    data: {uid: "demo-runner", reservedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-runner",
    data: {
      uid: "demo-runner",
      username: "demo_runner",
      usernameNormalized: "demo_runner",
      displayName: "Maya Runner",
      bio: "Easy miles, trail mornings, and community runs.",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
      coverUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1600&q=85",
      websiteUrl: "https://reemove.app/u/demo_runner",
      primarySportId: "running",
      role: "athlete",
      isVerified: true,
      verificationType: "athlete",
      professionalDetails: {
        headline: "Competitive distance runner",
        organization: "Haifa Running Club",
        positionOrCategory: "10K athlete",
        yearsExperience: 8,
        specialties: ["distance running", "mobility"],
        acceptingClients: false,
      },
      favoriteSportIds: ["running", "gym"],
      sportLevels: {running: "advanced", gym: "intermediate"},
      goals: ["improve_endurance", "find_training_partners"],
      location: new GeoPoint(32.8191, 34.9569),
      geohash: "svbcw",
      locality: "Haifa",
      administrativeArea: "Haifa District",
      countryCode: "IL",
      discoveryRadiusKm: 25,
      visibility: "public",
      followApprovalPolicy: "automatic",
      followersCount: 1,
      followingCount: 0,
      postsCount: 1,
      reelsCount: 1,
      onboardingCompleted: true,
      onboardingVersion: 1,
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "users/demo-runner/private/profile",
    data: {
      uid: "demo-runner",
      email: "runner@demo.reemove.app",
      emailNormalized: "runner@demo.reemove.app",
      providerIds: ["password"],
      accountStatus: "active",
      lastSignInAt: createdAt,
      dateOfBirth: "1998-04-12",
      ageBand: "25_34",
      isMinor: false,
      onboardingVersion: 1,
      onboardingCompletedAt: createdAt,
      schemaVersion: currentSchemaVersion,
      createdAt,
      updatedAt: createdAt,
    },
  },
  {
    path: "users/demo-athlete/following/demo-runner",
    data: {userId: "demo-runner", createdAt, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-runner/followers/demo-athlete",
    data: {userId: "demo-athlete", createdAt, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-athlete/private/profile_settings",
    data: {
      uid: "demo-athlete",
      followApprovalPolicy: "approvalRequired",
      messageAudience: "followers",
      mentionAudience: "everyone",
      tagAudience: "followers",
      showActivityStatus: true,
      showSportLevels: true,
      showGoals: true,
      showLocation: true,
      showFollowerLists: true,
      hideLikeCounts: false,
      discoverableByUsername: true,
      personalizedSuggestions: true,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "users/demo-runner/private/profile_settings",
    data: {
      uid: "demo-runner",
      followApprovalPolicy: "automatic",
      messageAudience: "everyone",
      mentionAudience: "everyone",
      tagAudience: "followers",
      showActivityStatus: true,
      showSportLevels: true,
      showGoals: true,
      showLocation: true,
      showFollowerLists: true,
      hideLikeCounts: false,
      discoverableByUsername: true,
      personalizedSuggestions: true,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "follow_requests/demo-newcomer--demo-athlete",
    data: {
      requesterId: "demo-newcomer",
      targetId: "demo-athlete",
      status: "pending",
      createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "verification_requests/demo-athlete",
    data: {
      uid: "demo-athlete",
      requestedType: "athlete",
      status: "pending",
      legalName: "ReeMove Athlete",
      summary: "Community football athlete requesting an authenticity review.",
      evidence: [{
        storagePath: "verification/demo-athlete/demo-athlete/seed-evidence.jpg",
        label: "Competition registration",
      }],
      submittedAt: createdAt,
      reviewedAt: null,
      rejectionReason: null,
      createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "posts/demo-run-finish",
    data: {
      authorId: "demo-runner",
      authorSnapshot: {
        id: "demo-runner",
        username: "demo_runner",
        displayName: "Maya Runner",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
        isVerified: true,
        verificationType: "athlete",
      },
      kind: "post",
      caption: "Sunrise tempo complete. Eight controlled kilometres and a calm finish. #running #haifa",
      media: [{
        id: "seed-run-image",
        storagePath: "seed/external/run.jpg",
        kind: "image",
        processingState: "ready",
        downloadUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=85",
        width: 1400,
        height: 933,
        contentType: "image/jpeg",
      }],
      hashtags: ["running", "haifa"],
      mentions: [],
      sportId: "running",
      locationLabel: "Haifa Promenade",
      visibility: "public",
      moderationState: "active",
      status: "published",
      allowComments: true,
      likeCount: 36,
      commentCount: 1,
      saveCount: 4,
      repostCount: 2,
      viewCount: 188,
      rankingScore: 92.5,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T11:20:00.000Z")),
      ...audit,
    },
  },
  {
    path: "posts/demo-training-carousel",
    data: {
      authorId: "demo-athlete",
      authorSnapshot: {
        id: "demo-athlete",
        username: "demo_athlete",
        displayName: "ReeMove Athlete",
        isVerified: false,
        verificationType: "none",
      },
      kind: "post",
      caption: "Strength day: clean reps, steady progress, and no skipped warm-up. #gym #progress",
      media: [
        {
          id: "seed-gym-1",
          storagePath: "seed/external/gym-1.jpg",
          kind: "image",
          processingState: "ready",
          downloadUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=85",
          width: 1400,
          height: 933,
          contentType: "image/jpeg",
        },
        {
          id: "seed-gym-2",
          storagePath: "seed/external/gym-2.jpg",
          kind: "image",
          processingState: "ready",
          downloadUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1400&q=85",
          width: 1400,
          height: 933,
          contentType: "image/jpeg",
        },
      ],
      hashtags: ["gym", "progress"],
      mentions: [],
      sportId: "gym",
      locationLabel: "Haifa Performance Gym",
      visibility: "public",
      moderationState: "active",
      status: "published",
      allowComments: true,
      likeCount: 18,
      commentCount: 0,
      saveCount: 3,
      repostCount: 1,
      viewCount: 104,
      rankingScore: 78.0,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T10:15:00.000Z")),
      ...audit,
    },
  },
  {
    path: "posts/demo-running-reel",
    data: {
      authorId: "demo-runner",
      authorSnapshot: {
        id: "demo-runner",
        username: "demo_runner",
        displayName: "Maya Runner",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
        isVerified: true,
        verificationType: "athlete",
      },
      kind: "reel",
      caption: "Quick feet before the main set. #runningdrills",
      media: [{
        id: "seed-reel-video",
        storagePath: "seed/external/bee.mp4",
        kind: "video",
        processingState: "ready",
        downloadUrl: "https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4",
        thumbnailUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=80",
        width: 720,
        height: 1280,
        durationMs: 7000,
        contentType: "video/mp4",
      }],
      hashtags: ["runningdrills"],
      mentions: [],
      sportId: "running",
      visibility: "public",
      moderationState: "active",
      status: "published",
      allowComments: true,
      likeCount: 61,
      commentCount: 0,
      saveCount: 11,
      repostCount: 5,
      viewCount: 430,
      rankingScore: 99.0,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T09:45:00.000Z")),
      ...audit,
    },
  },
  {
    path: "posts/demo-run-finish/comments/seed-comment",
    data: {
      postId: "demo-run-finish",
      authorId: "demo-athlete",
      authorSnapshot: {
        id: "demo-athlete",
        username: "demo_athlete",
        displayName: "ReeMove Athlete",
        isVerified: false,
        verificationType: "none",
      },
      text: "Strong finish. See you at the weekend run!",
      parentCommentId: null,
      likeCount: 2,
      replyCount: 0,
      moderationState: "active",
      createdAt: Timestamp.fromDate(new Date("2026-07-13T11:32:00.000Z")),
      updatedAt: Timestamp.fromDate(new Date("2026-07-13T11:32:00.000Z")),
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "feed_entries/demo-athlete--demo-run-finish",
    data: {
      recipientId: "demo-athlete",
      postId: "demo-run-finish",
      authorId: "demo-runner",
      source: "following",
      rankingScore: 92.5,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T11:20:00.000Z")),
      createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "feed_entries/demo-athlete--demo-running-reel",
    data: {
      recipientId: "demo-athlete",
      postId: "demo-running-reel",
      authorId: "demo-runner",
      source: "following",
      rankingScore: 99.0,
      publishedAt: Timestamp.fromDate(new Date("2026-07-13T09:45:00.000Z")),
      createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "content_reactions/demo-athlete--demo-run-finish",
    data: {
      uid: "demo-athlete",
      postId: "demo-run-finish",
      liked: true,
      saved: false,
      reposted: false,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "stories/demo-runner-morning",
    data: {
      authorId: "demo-runner",
      authorSnapshot: {
        id: "demo-runner",
        username: "demo_runner",
        displayName: "Maya Runner",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
        isVerified: true,
        verificationType: "athlete",
      },
      media: {
        id: "seed-story-image",
        storagePath: "seed/external/story.jpg",
        kind: "image",
        processingState: "ready",
        downloadUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=900&q=85",
        width: 900,
        height: 1600,
        contentType: "image/jpeg",
      },
      caption: "First light, first kilometres.",
      sportId: "running",
      visibility: "public",
      moderationState: "active",
      viewCount: 12,
      createdAt: Timestamp.fromDate(new Date("2026-07-13T11:00:00.000Z")),
      updatedAt: Timestamp.fromDate(new Date("2026-07-13T11:00:00.000Z")),
      expiresAt: Timestamp.fromDate(new Date("2026-07-14T11:00:00.000Z")),
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "places/haifa-performance-gym",
    data: {
      name: "Haifa Performance Gym",
      description: "Strength, functional training, and coached sessions.",
      type: "gym",
      sportIds: ["gym"],
      location: new GeoPoint(32.7940, 34.9896),
      geohash: "svbcr",
      addressLine: "10 Sports Avenue",
      city: "Haifa",
      countryCode: "IL",
      media: [],
      pricingText: "Day passes and monthly plans available",
      rating: 4.8,
      reviewCount: 128,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "places/tamra-community-pitch",
    data: {
      name: "Tamra Community Pitch",
      description: "Outdoor football pitch for community matches.",
      type: "pitch",
      sportIds: ["football"],
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      addressLine: "Community Sports Complex",
      city: "Tamra",
      countryCode: "IL",
      media: [],
      rating: 4.5,
      reviewCount: 54,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "places/haifa-coastal-running-track",
    data: {
      name: "Haifa Coastal Running Track",
      description: "A flat seafront route suited to easy runs and intervals.",
      type: "track",
      sportIds: ["running"],
      location: new GeoPoint(32.8191, 34.9569),
      geohash: "svbcw",
      addressLine: "Haifa Promenade",
      city: "Haifa",
      countryCode: "IL",
      media: [],
      rating: 4.7,
      reviewCount: 203,
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  {
    path: "events/community-football-august",
    data: {
      ownerId: "demo-athlete",
      sportId: "football",
      type: "match",
      title: "Saturday Community Football",
      description: "Friendly seven-a-side match. Bring water and arrive 15 minutes early.",
      startAt: eventStart,
      endAt: eventEnd,
      timezone: "Asia/Jerusalem",
      location: new GeoPoint(32.8530, 35.1987),
      geohash: "svbfq",
      locality: "Tamra",
      countryCode: "IL",
      placeId: "tamra-community-pitch",
      capacity: 14,
      attendeeCount: 1,
      minimumLevel: "beginner",
      maximumLevel: "advanced",
      price: {amountMinor: 0, currency: "ILS"},
      visibility: "public",
      status: "published",
      moderationState: "active",
      media: [],
      ...audit,
    },
  },
  ...[
    {
      id: "steady-runner", name: "Steady Runner",
      description: "Completed a safe weekly running consistency challenge.",
      rarity: "common", sportId: "running",
    },
    {
      id: "consistent-lifter", name: "Consistent Lifter",
      description: "Completed a technique-first gym consistency challenge.",
      rarity: "common", sportId: "gym",
    },
    {
      id: "football-rhythm", name: "Football Rhythm",
      description: "Completed a verified football skills week.",
      rarity: "common", sportId: "football",
    },
  ].map((badge) => ({
    path: `challenge_badges/${badge.id}`,
    data: {...badge, iconUrl: null, isActive: true, ...audit},
  })),
  {
    path: "challenge_rewards/local-sports-10",
    data: {
      title: "Local sports partner reward",
      description: "A sponsor-provided reward for verified challenge completion.",
      type: "discount",
      valueText: "10% off an eligible purchase",
      sponsorName: "ReeMove Partner",
      expiresAt: Timestamp.fromDate(new Date("2026-12-31T21:59:59.000Z")),
      isActive: true,
      ...audit,
    },
  },
  {
    path: "challenges/weekly-5k-consistency",
    data: {
      creatorId: "system",
      creatorName: "ReeMove Coach",
      sportId: "running",
      title: "Weekly 5K Consistency",
      description: "Record five kilometres across comfortable sessions this week. Rest, hydration, and pain-free movement come first.",
      source: "official",
      status: "active",
      difficulty: "beginner",
      startsAt: challengeStart,
      endsAt: challengeEnd,
      rules: [{
        metric: "distance", target: 5, unit: "km",
        verificationMethod: "automaticActivity", maximumDailyProgress: 5,
      }],
      safetyPolicy: {
        minimumAge: 14, requiresRestDays: true, maximumEffortMinutesPerDay: 90,
        prohibitedBehaviors: ["continuing through pain", "sleep or hydration deprivation", "unsafe route choices"],
        healthDisclaimer: "Stop if you feel pain, dizziness, or unusual discomfort and seek qualified help.",
      },
      media: [], participantCount: 1, completionCount: 0,
      badgeId: "steady-runner", rewardIds: ["local-sports-10"],
      visibility: "public", moderationState: "active", isFeatured: true,
      ...audit,
    },
  },
  {
    path: "challenges/gym-three-quality-sessions",
    data: {
      creatorId: "system", creatorName: "ReeMove Coach", sportId: "gym",
      title: "Three Quality Sessions",
      description: "Complete three planned gym sessions with controlled technique, appropriate loads, and recovery between sessions.",
      source: "official", status: "active", difficulty: "beginner",
      startsAt: challengeStart, endsAt: challengeEnd,
      rules: [{
        metric: "sessions", target: 3, unit: "sessions",
        verificationMethod: "automaticActivity", maximumDailyProgress: 1,
      }],
      safetyPolicy: {
        minimumAge: 14, requiresRestDays: true, maximumEffortMinutesPerDay: 90,
        prohibitedBehaviors: ["unsafe equipment use", "maximal attempts without supervision", "continuing through pain"],
        healthDisclaimer: "Use appropriate technique and supervision. Stop if you feel pain, dizziness, or unusual discomfort.",
      },
      media: [], participantCount: 1, completionCount: 0,
      badgeId: "consistent-lifter", rewardIds: [],
      visibility: "public", moderationState: "active", isFeatured: true,
      ...audit,
    },
  },
  {
    path: "challenges/football-skills-week",
    data: {
      creatorId: "demo-athlete", creatorName: "ReeMove Athlete", sportId: "football",
      title: "Football Skills Week",
      description: "Complete two verified football practice sessions focused on controlled skill work, teamwork, and safe participation.",
      source: "community", status: "active", difficulty: "beginner",
      startsAt: challengeStart, endsAt: challengeEnd,
      rules: [{
        metric: "sessions", target: 2, unit: "sessions",
        verificationMethod: "organizerReview", maximumDailyProgress: 1,
      }],
      safetyPolicy: {
        minimumAge: 14, requiresRestDays: true, maximumEffortMinutesPerDay: 90,
        prohibitedBehaviors: ["dangerous tackles", "continuing through injury", "unsafe playing surfaces"],
        healthDisclaimer: "Warm up, use suitable equipment, and stop if you feel pain or unusual discomfort.",
      },
      media: [], participantCount: 1, completionCount: 0,
      badgeId: "football-rhythm", rewardIds: [],
      visibility: "public", moderationState: "active", isFeatured: false,
      ...audit,
    },
  },
  {
    path: "challenges/weekly-5k-consistency/participants/demo-runner",
    data: {
      challengeId: "weekly-5k-consistency", userId: "demo-runner",
      status: "active", progress: 3.2, progressPercent: 64, rank: 1,
      joinedAt: createdAt, lastSubmissionAt: createdAt, reminderEnabled: true,
      lastReminderAt: null, completedAt: null, ...audit,
    },
  },
  {
    path: "challenges/weekly-5k-consistency/leaderboard/demo-runner",
    data: {
      userId: "demo-runner", displayName: "Maya Runner", username: "maya_runner",
      avatarUrl: null, progress: 3.2, progressPercent: 64, rank: 1,
      verifiedAt: createdAt, ...audit,
    },
  },
  {
    path: "challenges/gym-three-quality-sessions/participants/demo-athlete",
    data: {
      challengeId: "gym-three-quality-sessions", userId: "demo-athlete",
      status: "active", progress: 1, progressPercent: 33.33, rank: 1,
      joinedAt: createdAt, lastSubmissionAt: createdAt, reminderEnabled: true,
      lastReminderAt: null, completedAt: null, ...audit,
    },
  },
  {
    path: "challenges/gym-three-quality-sessions/leaderboard/demo-athlete",
    data: {
      userId: "demo-athlete", displayName: "ReeMove Athlete", username: "demo_athlete",
      avatarUrl: null, progress: 1, progressPercent: 33.33, rank: 1,
      verifiedAt: createdAt, ...audit,
    },
  },
  {
    path: "challenges/football-skills-week/participants/demo-athlete",
    data: {
      challengeId: "football-skills-week", userId: "demo-athlete",
      status: "active", progress: 0, progressPercent: 0, rank: 1,
      joinedAt: createdAt, lastSubmissionAt: null, reminderEnabled: false,
      lastReminderAt: null, completedAt: null, ...audit,
    },
  },
  {
    path: "marketplace_listings/demo-adjustable-bench",
    data: {
      sellerId: "demo-athlete",
      seller: {
        uid: "demo-athlete",
        username: "demo_athlete",
        displayName: "ReeMove Athlete",
        isVerified: false,
        verificationType: "none",
      },
      title: "Adjustable Training Bench",
      description: "Well-maintained adjustable bench suitable for a home gym.",
      categoryId: "gym_equipment",
      sportId: "gym",
      condition: "good",
      price: {amountMinor: 55000, currency: "ILS"},
      isNegotiable: true,
      deliveryOptions: ["pickup"],
      media: [],
      location: new GeoPoint(32.8530, 35.1987),
      geohash: geohashForLocation([32.8530, 35.1987]),
      locality: "Tamra",
      countryCode: "IL",
      searchPrefixes: ["ad", "adj", "adjustable", "be", "bench", "tr", "training"],
      status: "active",
      favoriteCount: 0,
      viewCount: 4,
      conversationCount: 0,
      publishedAt: createdAt,
      expiresAt: Timestamp.fromDate(new Date("2026-09-12T12:00:00.000Z")),
      moderationState: "active",
      ...audit,
    },
  },
  ...[
    {id: "football_gear", name: "Football gear", sportIds: ["football"], sortOrder: 10},
    {id: "gym_equipment", name: "Gym equipment", sportIds: ["gym"], sortOrder: 20},
    {id: "running_gear", name: "Running gear", sportIds: ["running"], sortOrder: 30},
    {id: "wearables", name: "Wearables", sportIds: [], sortOrder: 40},
    {id: "apparel", name: "Sports apparel", sportIds: [], sortOrder: 50},
    {id: "recovery", name: "Recovery equipment", sportIds: [], sortOrder: 60},
    {id: "other", name: "Other sports equipment", sportIds: [], sortOrder: 70},
  ].map((category) => ({
    path: `marketplace_categories/${category.id}`,
    data: {
      name: category.name,
      sportIds: category.sportIds,
      isActive: true,
      sortOrder: category.sortOrder,
      ...audit,
    },
  })),
  ...[
    {
      id: "demo-adjustable-dumbbells",
      sellerId: "demo-athlete",
      seller: {uid: "demo-athlete", username: "demo_athlete", displayName: "ReeMove Athlete", isVerified: false, verificationType: "none"},
      title: "Adjustable dumbbells 20 kg pair",
      description: "Clean adjustable pair with secure collars and all plates shown. Minor cosmetic marks only.",
      categoryId: "gym_equipment", sportId: "gym", condition: "good",
      price: {amountMinor: 68000, currency: "ILS"}, isNegotiable: true,
      deliveryOptions: ["pickup", "meetup"],
      imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1400&q=85",
      location: new GeoPoint(32.794, 34.990), locality: "Haifa", administrativeArea: "Haifa District",
      searchPrefixes: ["ad", "adj", "adju", "adjustable", "du", "dumbbells", "we", "weights"],
    },
    {
      id: "demo-football-boots",
      sellerId: "demo-runner",
      seller: {uid: "demo-runner", username: "maya_runner", displayName: "Maya Runner", isVerified: true, verificationType: "athlete"},
      title: "Firm-ground football boots size 42",
      description: "Lightly used boots with intact studs and clean insoles. Best for natural grass pitches.",
      categoryId: "football_gear", sportId: "football", condition: "likeNew",
      price: {amountMinor: 24000, currency: "ILS"}, isNegotiable: false,
      deliveryOptions: ["meetup", "shipping"],
      imageUrl: "https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=1400&q=85",
      location: new GeoPoint(32.820, 34.960), locality: "Haifa", administrativeArea: "Haifa District",
      searchPrefixes: ["fo", "foo", "football", "bo", "boo", "boots", "si", "size"],
    },
    {
      id: "demo-running-watch",
      sellerId: "demo-runner",
      seller: {uid: "demo-runner", username: "maya_runner", displayName: "Maya Runner", isVerified: true, verificationType: "athlete"},
      title: "GPS running watch with charger",
      description: "Reliable GPS watch with heart-rate tracking, original charger, and a recently replaced strap.",
      categoryId: "wearables", sportId: "running", condition: "good",
      price: {amountMinor: 52000, currency: "ILS"}, isNegotiable: true,
      deliveryOptions: ["pickup", "meetup", "shipping"],
      imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=85",
      location: new GeoPoint(32.820, 34.960), locality: "Haifa", administrativeArea: "Haifa District",
      searchPrefixes: ["gp", "gps", "ru", "run", "running", "wa", "wat", "watch"],
    },
  ].map((listing, index) => ({
    path: `marketplace_listings/${listing.id}`,
    data: {
      sellerId: listing.sellerId,
      seller: listing.seller,
      title: listing.title,
      description: listing.description,
      categoryId: listing.categoryId,
      sportId: listing.sportId,
      condition: listing.condition,
      price: listing.price,
      isNegotiable: listing.isNegotiable,
      deliveryOptions: listing.deliveryOptions,
      media: [{
        id: `seed-marketplace-${index + 1}`,
        storagePath: `seed/marketplace/${listing.id}.jpg`,
        kind: "image",
        processingState: "ready",
        downloadUrl: listing.imageUrl,
        contentType: "image/jpeg",
        sizeBytes: 1024,
      }],
      location: listing.location,
      geohash: geohashForLocation([listing.location.latitude, listing.location.longitude]),
      locality: listing.locality,
      administrativeArea: listing.administrativeArea,
      countryCode: "IL",
      searchPrefixes: listing.searchPrefixes,
      status: "active",
      moderationState: "active",
      favoriteCount: index === 0 ? 1 : 0,
      viewCount: 12 + index * 7,
      conversationCount: index,
      publishedAt: createdAt,
      expiresAt: Timestamp.fromDate(new Date("2026-09-12T12:00:00.000Z")),
      ...audit,
    },
  })),
  {
    path: "users/demo-athlete/marketplace_favorites/demo-football-boots",
    data: {userId: "demo-athlete", listingId: "demo-football-boots", createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-athlete/private/marketplace_stats",
    data: {activeListingCount: 2, soldListingCount: 0, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "users/demo-runner/private/marketplace_stats",
    data: {activeListingCount: 2, soldListingCount: 0, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: `conversations/${directSeedConversationId}`,
    data: {
      type: "direct", title: "Maya Runner", createdBy: "demo-athlete",
      memberCount: 2, moderationState: "active",
      lastMessage: {id: "seed-message-2", senderId: "demo-runner", kind: "text", preview: "Perfect, see you there!", sentAt: createdAt},
      ...audit,
    },
  },
  {
    path: `conversations/${directSeedConversationId}/members/demo-athlete`,
    data: {userId: "demo-athlete", userSnapshot: athleteMessageSnapshot, role: "owner", joinedAt: createdAt, lastReadAt: createdAt, unreadCount: 1, notificationsEnabled: true, mutedUntil: null, archivedAt: null, removedAt: null, ...audit},
  },
  {
    path: `conversations/${directSeedConversationId}/members/demo-runner`,
    data: {userId: "demo-runner", userSnapshot: runnerMessageSnapshot, role: "member", joinedAt: createdAt, lastReadAt: createdAt, unreadCount: 0, notificationsEnabled: true, mutedUntil: null, archivedAt: null, removedAt: null, ...audit},
  },
  {
    path: `conversations/${directSeedConversationId}/messages/seed-message-1`,
    data: {conversationId: directSeedConversationId, senderId: "demo-athlete", senderSnapshot: athleteMessageSnapshot, kind: "text", text: "Easy run tomorrow at 7?", attachments: [], replyTo: null, reactionCounts: {"🔥": 1}, isDeleted: false, sentAt: Timestamp.fromDate(new Date("2026-07-13T11:58:00.000Z")), editedAt: null, ...audit},
  },
  {
    path: `conversations/${directSeedConversationId}/messages/seed-message-2`,
    data: {conversationId: directSeedConversationId, senderId: "demo-runner", senderSnapshot: runnerMessageSnapshot, kind: "text", text: "Perfect, see you there!", attachments: [], replyTo: null, reactionCounts: {}, isDeleted: false, sentAt: createdAt, editedAt: null, ...audit},
  },
  {
    path: `users/demo-athlete/conversation_inbox/${directSeedConversationId}`,
    data: {conversationId: directSeedConversationId, type: "direct", title: "Maya Runner", avatarUrl: null, memberSnapshots: [athleteMessageSnapshot, runnerMessageSnapshot], lastMessage: {id: "seed-message-2", senderId: "demo-runner", kind: "text", preview: "Perfect, see you there!", sentAt: createdAt}, unreadCount: 1, notificationsEnabled: true, mutedUntil: null, archivedAt: null, removedAt: null, isArchived: false, ...audit},
  },
  {
    path: `users/demo-runner/conversation_inbox/${directSeedConversationId}`,
    data: {conversationId: directSeedConversationId, type: "direct", title: "ReeMove Athlete", avatarUrl: null, memberSnapshots: [athleteMessageSnapshot, runnerMessageSnapshot], lastMessage: {id: "seed-message-2", senderId: "demo-runner", kind: "text", preview: "Perfect, see you there!", sentAt: createdAt}, unreadCount: 0, notificationsEnabled: true, mutedUntil: null, archivedAt: null, removedAt: null, isArchived: false, ...audit},
  },
  {
    path: `users/demo-athlete/message_reactions/${directSeedConversationId}--seed-message-1`,
    data: {conversationId: directSeedConversationId, messageId: "seed-message-1", emojis: ["🔥"], updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: `conversations/${groupSeedConversationId}`,
    data: {type: "group", title: "Weekend Training", createdBy: "demo-athlete", memberCount: 3, moderationState: "active", lastMessage: {id: "group-seed-message-1", senderId: "demo-athlete", kind: "text", preview: "Saturday at 10 — football then recovery run.", sentAt: createdAt}, ...audit},
  },
  ...[
    {id: "demo-athlete", snapshot: athleteMessageSnapshot, role: "owner"},
    {id: "demo-runner", snapshot: runnerMessageSnapshot, role: "admin"},
    {id: "demo-newcomer", snapshot: newcomerMessageSnapshot, role: "member"},
  ].map((member) => ({
    path: `conversations/${groupSeedConversationId}/members/${member.id}`,
    data: {userId: member.id, userSnapshot: member.snapshot, role: member.role, joinedAt: createdAt, lastReadAt: createdAt, unreadCount: 0, notificationsEnabled: true, mutedUntil: null, archivedAt: null, removedAt: null, ...audit},
  })),
  {
    path: `conversations/${groupSeedConversationId}/messages/group-seed-message-1`,
    data: {conversationId: groupSeedConversationId, senderId: "demo-athlete", senderSnapshot: athleteMessageSnapshot, kind: "text", text: "Saturday at 10 — football then recovery run.", attachments: [], replyTo: null, reactionCounts: {"💪": 2}, isDeleted: false, sentAt: createdAt, editedAt: null, ...audit},
  },
  ...[
    {id: "demo-athlete", snapshot: athleteMessageSnapshot},
    {id: "demo-runner", snapshot: runnerMessageSnapshot},
    {id: "demo-newcomer", snapshot: newcomerMessageSnapshot},
  ].map((member) => ({
    path: `users/${member.id}/conversation_inbox/${groupSeedConversationId}`,
    data: {conversationId: groupSeedConversationId, type: "group", title: "Weekend Training", memberSnapshots: [athleteMessageSnapshot, runnerMessageSnapshot, newcomerMessageSnapshot], lastMessage: {id: "group-seed-message-1", senderId: "demo-athlete", kind: "text", preview: "Saturday at 10 — football then recovery run.", sentAt: createdAt}, unreadCount: 0, notificationsEnabled: true, mutedUntil: null, archivedAt: null, removedAt: null, isArchived: false, ...audit},
  })),
  {
    path: "teams/tamra-seven-a-side",
    data: {
      sportId: "football", ownerId: "demo-athlete", name: "Tamra Seven-a-Side",
      description: "Friendly but organized weekly football for intermediate local players.",
      type: "team", joinPolicy: "approvalRequired", memberCount: 2, capacity: 18,
      tags: ["seven-a-side", "weekly", "intermediate"], city: "Tamra", countryCode: "IL",
      pricingText: "Pitch cost shared per match", isVerified: true,
      visibility: "public", moderationState: "active", ...audit,
    },
  },
  {
    path: "teams/tamra-seven-a-side/members/demo-athlete",
    data: {userId: "demo-athlete", userSnapshot: athleteMessageSnapshot, role: "owner", status: "active", joinedAt: createdAt, removedAt: null, ...audit},
  },
  {
    path: "teams/tamra-seven-a-side/members/demo-runner",
    data: {userId: "demo-runner", userSnapshot: runnerMessageSnapshot, role: "member", status: "active", joinedAt: createdAt, removedAt: null, ...audit},
  },
  {
    path: "teams/tamra-seven-a-side/members/demo-newcomer",
    data: {userId: "demo-newcomer", userSnapshot: newcomerMessageSnapshot, role: "pending", status: "pending", joinedAt: createdAt, removedAt: null, ...audit},
  },
  {
    path: "teams/haifa-strength-circle",
    data: {
      sportId: "gym", ownerId: "demo-athlete", name: "Haifa Strength Circle",
      description: "A supportive group for progressive strength training and technique review.",
      type: "trainingGroup", joinPolicy: "open", memberCount: 1, capacity: 40,
      tags: ["strength", "technique", "beginner-friendly"], city: "Haifa", countryCode: "IL",
      pricingText: "Free community group", isVerified: false,
      visibility: "public", moderationState: "active", ...audit,
    },
  },
  {
    path: "teams/haifa-strength-circle/members/demo-athlete",
    data: {userId: "demo-athlete", userSnapshot: athleteMessageSnapshot, role: "owner", status: "active", joinedAt: createdAt, removedAt: null, ...audit},
  },
  {
    path: "teams/haifa-sunrise-runners",
    data: {
      sportId: "running", ownerId: "demo-runner", name: "Haifa Sunrise Runners",
      description: "Easy and tempo coastal runs before the city wakes up.",
      type: "club", joinPolicy: "open", memberCount: 2, capacity: 80,
      tags: ["5k", "10k", "coastal", "morning"], city: "Haifa", countryCode: "IL",
      isVerified: true, visibility: "public", moderationState: "active", ...audit,
    },
  },
  {
    path: "teams/haifa-sunrise-runners/members/demo-runner",
    data: {userId: "demo-runner", userSnapshot: runnerMessageSnapshot, role: "owner", status: "active", joinedAt: createdAt, removedAt: null, ...audit},
  },
  {
    path: "teams/haifa-sunrise-runners/members/demo-athlete",
    data: {userId: "demo-athlete", userSnapshot: athleteMessageSnapshot, role: "member", status: "active", joinedAt: createdAt, removedAt: null, ...audit},
  },
  {
    path: "events/haifa-strength-foundations",
    data: {
      ownerId: "demo-runner", ownerSnapshot: runnerMessageSnapshot, sportId: "gym",
      type: "classSession", title: "Strength Foundations Workshop",
      description: "A coached session covering squat, press, bracing, and safe progression.",
      startAt: Timestamp.fromDate(new Date("2026-08-12T16:30:00.000Z")),
      endAt: Timestamp.fromDate(new Date("2026-08-12T18:00:00.000Z")),
      timezone: "Asia/Jerusalem", location: new GeoPoint(32.7940, 34.9896), geohash: "svbcr",
      locality: "Haifa", countryCode: "IL", placeId: "haifa-performance-gym",
      capacity: 16, attendeeCount: 1, waitlistCount: 0,
      minimumLevel: "beginner", maximumLevel: "intermediate",
      price: {amountMinor: 8000, currency: "ILS"}, visibility: "public",
      status: "published", moderationState: "active", media: [], ...audit,
    },
  },
  {
    path: "events/haifa-strength-foundations/attendees/demo-runner",
    data: {userId: "demo-runner", userSnapshot: runnerMessageSnapshot, status: "attending", joinedAt: createdAt, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "events/coastal-10k-social",
    data: {
      ownerId: "demo-runner", ownerSnapshot: runnerMessageSnapshot, sportId: "running",
      type: "meetup", title: "Coastal 10K Social Run",
      description: "Conversational 10K with pace groups and coffee after the run.",
      startAt: Timestamp.fromDate(new Date("2026-08-15T03:30:00.000Z")),
      endAt: Timestamp.fromDate(new Date("2026-08-15T05:00:00.000Z")),
      timezone: "Asia/Jerusalem", location: new GeoPoint(32.8191, 34.9569), geohash: "svbcw",
      locality: "Haifa", countryCode: "IL", placeId: "haifa-coastal-running-track",
      capacity: 60, attendeeCount: 2, waitlistCount: 0,
      minimumLevel: "beginner", maximumLevel: "advanced",
      visibility: "public", status: "published", moderationState: "active", media: [], ...audit,
    },
  },
  {
    path: "events/coastal-10k-social/attendees/demo-runner",
    data: {userId: "demo-runner", userSnapshot: runnerMessageSnapshot, status: "attending", joinedAt: createdAt, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "events/coastal-10k-social/attendees/demo-athlete",
    data: {userId: "demo-athlete", userSnapshot: athleteMessageSnapshot, status: "attending", joinedAt: createdAt, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "events/community-football-august/attendees/demo-athlete",
    data: {userId: "demo-athlete", userSnapshot: athleteMessageSnapshot, status: "attending", joinedAt: createdAt, updatedAt: createdAt, schemaVersion: currentSchemaVersion},
  },
  {
    path: "trainer_profiles/demo-runner",
    data: {
      userId: "demo-runner", displayName: "Maya Runner", username: "demo_runner",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
      bio: "Distance-running coach focused on sustainable progression and strength support.",
      headline: "Certified running and conditioning coach", sportIds: ["running", "gym"],
      specialties: ["10K programming", "running form", "strength for runners"],
      yearsExperience: 8, rating: 4.9, reviewCount: 47, city: "Haifa", countryCode: "IL",
      acceptingClients: true, isVerified: true,
      minimumPrice: {amountMinor: 12000, currency: "ILS"}, moderationState: "active", ...audit,
    },
  },
  {
    path: "trainer_services/maya-running-consultation",
    data: {
      trainerId: "demo-runner", sportId: "running", title: "Running plan consultation",
      description: "A 60-minute assessment and a four-week personalized running structure.",
      type: "consultation", deliveryMode: "hybrid", durationMinutes: 60,
      price: {amountMinor: 18000, currency: "ILS"}, isActive: true,
      moderationState: "active", ...audit,
    },
  },
  {
    path: "trainer_services/maya-strength-for-runners",
    data: {
      trainerId: "demo-runner", sportId: "gym", title: "Strength for runners",
      description: "Technique-led strength session for durable running performance.",
      type: "personalTraining", deliveryMode: "inPerson", durationMinutes: 75,
      price: {amountMinor: 15000, currency: "ILS"}, isActive: true,
      moderationState: "active", ...audit,
    },
  },
  ...[
    {id: "football_weekly", sportId: "football", title: "Weekly football form", metric: "matchPoints", unit: "points", entries: [
      {userId: "demo-athlete", displayName: "ReeMove Athlete", username: "demo_athlete", rank: 1, value: 18, formattedValue: "18 points", trend: 1},
      {userId: "demo-runner", displayName: "Maya Runner", username: "demo_runner", rank: 2, value: 12, formattedValue: "12 points", trend: 0},
    ]},
    {id: "gym_weekly", sportId: "gym", title: "Weekly training volume", metric: "volumeKg", unit: "kg", entries: [
      {userId: "demo-athlete", displayName: "ReeMove Athlete", username: "demo_athlete", rank: 1, value: 12450, formattedValue: "12,450 kg", trend: 1},
      {userId: "demo-runner", displayName: "Maya Runner", username: "demo_runner", rank: 2, value: 8200, formattedValue: "8,200 kg", trend: -1},
    ]},
    {id: "running_weekly", sportId: "running", title: "Weekly distance", metric: "distanceKm", unit: "km", entries: [
      {userId: "demo-runner", displayName: "Maya Runner", username: "demo_runner", rank: 1, value: 52.4, formattedValue: "52.4 km", trend: 1},
      {userId: "demo-athlete", displayName: "ReeMove Athlete", username: "demo_athlete", rank: 2, value: 21.7, formattedValue: "21.7 km", trend: 0},
    ]},
  ].map((leaderboard) => ({
    path: `leaderboards/${leaderboard.id}`,
    data: {sportId: leaderboard.sportId, title: leaderboard.title, metric: leaderboard.metric,
      unit: leaderboard.unit, period: "weekly", topEntries: leaderboard.entries,
      isPublished: true, generatedAt: createdAt, startsAt: challengeStart,
      endsAt: challengeEnd, ...audit},
  })),
  ...[
    {id: "football-activity-demo", userId: "demo-athlete", sportId: "football", metrics: {matchPoints: 18}},
    {id: "gym-activity-demo", userId: "demo-athlete", sportId: "gym", metrics: {volumeKg: 12450}},
    {id: "running-activity-demo", userId: "demo-runner", sportId: "running", metrics: {distanceKm: 52.4}},
  ].map((activity) => ({
    path: `activities/${activity.id}`,
    data: {userId: activity.userId, sportId: activity.sportId, status: "verified",
      occurredAt: createdAt, metrics: activity.metrics, source: "seed", ...audit},
  })),
  {
    path: "sports_routes/haifa-coastal-5k-loop",
    data: {
      ownerId: "system",
      name: "Haifa Coastal 5K Loop",
      description: "A flat, well-known promenade loop for easy runs, tempo sessions, and community meetups.",
      sportIds: ["running"],
      routeType: "loop",
      difficulty: "easy",
      startLocation: new GeoPoint(32.8191, 34.9569),
      geohash: geohashForLocation([32.8191, 34.9569]),
      path: [
        new GeoPoint(32.8191, 34.9569),
        new GeoPoint(32.8224, 34.9596),
        new GeoPoint(32.8257, 34.9631),
        new GeoPoint(32.8230, 34.9670),
        new GeoPoint(32.8187, 34.9638),
        new GeoPoint(32.8191, 34.9569),
      ],
      distanceMeters: 5000,
      elevationGainMeters: 22,
      estimatedDurationMinutes: 34,
      surfaceTypes: ["paved", "promenade"],
      locality: "Haifa Promenade",
      city: "Haifa",
      countryCode: "IL",
      coverUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1600&q=85",
      isVerified: true,
      visibility: "public",
      moderationState: "active",
      ...audit,
    },
  },
  ...[
    {
      id: "place_haifa-performance-gym", type: "place", sourceId: "haifa-performance-gym",
      title: "Haifa Performance Gym", subtitle: "10 Sports Avenue", location: new GeoPoint(32.7940, 34.9896),
      sportIds: ["gym"], placeType: "gym", imageUrl: null, verified: true, rating: 4.8,
      city: "Haifa", countryCode: "IL", approximate: false,
    },
    {
      id: "place_tamra-community-pitch", type: "place", sourceId: "tamra-community-pitch",
      title: "Tamra Community Pitch", subtitle: "Community Sports Complex", location: new GeoPoint(32.8530, 35.1987),
      sportIds: ["football"], placeType: "pitch", imageUrl: null, verified: true, rating: 4.5,
      city: "Tamra", countryCode: "IL", approximate: false,
    },
    {
      id: "place_haifa-coastal-running-track", type: "place", sourceId: "haifa-coastal-running-track",
      title: "Haifa Coastal Running Track", subtitle: "Haifa Promenade", location: new GeoPoint(32.8191, 34.9569),
      sportIds: ["running"], placeType: "track", imageUrl: null, verified: true, rating: 4.7,
      city: "Haifa", countryCode: "IL", approximate: false,
    },
    {
      id: "event_haifa-strength-foundations", type: "event", sourceId: "haifa-strength-foundations",
      ownerId: "demo-runner", title: "Strength Foundations Workshop", subtitle: "Haifa",
      location: new GeoPoint(32.7940, 34.9896), sportIds: ["gym"], eventType: "classSession",
      imageUrl: null, startsAt: Timestamp.fromDate(new Date("2026-08-12T16:30:00.000Z")),
      endsAt: Timestamp.fromDate(new Date("2026-08-12T18:00:00.000Z")), capacity: 16,
      attendeeCount: 1, approximate: false,
    },
    {
      id: "event_coastal-10k-social", type: "event", sourceId: "coastal-10k-social",
      ownerId: "demo-runner", title: "Coastal 10K Social Run", subtitle: "Haifa",
      location: new GeoPoint(32.8191, 34.9569), sportIds: ["running"], eventType: "meetup",
      imageUrl: null, startsAt: Timestamp.fromDate(new Date("2026-08-15T03:30:00.000Z")),
      endsAt: Timestamp.fromDate(new Date("2026-08-15T05:00:00.000Z")), capacity: 60,
      attendeeCount: 2, approximate: false,
    },
    {
      id: "person_demo-runner", type: "person", sourceId: "demo-runner", ownerId: "demo-runner",
      title: "Maya Runner", subtitle: "running", username: "maya_runner",
      location: new GeoPoint(32.82, 34.96), sportIds: ["running", "gym"],
      imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
      verified: true, verificationType: "athlete", audienceSegment: "adult", approximate: true,
    },
    {
      id: "route_haifa-coastal-5k-loop", type: "route", sourceId: "haifa-coastal-5k-loop",
      ownerId: "system", title: "Haifa Coastal 5K Loop", subtitle: "Haifa Promenade",
      location: new GeoPoint(32.8191, 34.9569), sportIds: ["running"], routeType: "loop",
      imageUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1600&q=85",
      distanceMeters: 5000, elevationGainMeters: 22, difficulty: "easy",
      path: [
        new GeoPoint(32.8191, 34.9569), new GeoPoint(32.8224, 34.9596),
        new GeoPoint(32.8257, 34.9631), new GeoPoint(32.8230, 34.9670),
        new GeoPoint(32.8187, 34.9638), new GeoPoint(32.8191, 34.9569),
      ],
      verified: true, approximate: false,
    },
  ].map((entity) => ({
    path: `nearby_entities/${entity.id}`,
    data: {
      ...entity,
      geohash: geohashForLocation([entity.location.latitude, entity.location.longitude]),
      active: true,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  })),
  {
    path: "users/demo-athlete/notifications/seed-social-activity",
    data: {
      id: "seed-social-activity",
      recipientId: "demo-athlete",
      category: "activity",
      kind: "new_follower",
      title: "New follower",
      body: "Maya Runner started following you.",
      route: "/profile/user/maya_runner",
      groupKey: "new_followers",
      groupCount: 1,
      actors: [runnerMessageSnapshot],
      latestActorId: "demo-runner",
      entityType: "user",
      entityId: "demo-runner",
      data: {profileId: "demo-runner"},
      readAt: null,
      deletedAt: null,
      createdAt,
      latestAt: createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "users/demo-athlete/notifications/seed-message-activity",
    data: {
      id: "seed-message-activity",
      recipientId: "demo-athlete",
      category: "messages",
      kind: "conversation_message",
      title: "Maya Runner",
      body: "Perfect, see you there!",
      route: `/messages/${directSeedConversationId}`,
      groupKey: `conversation:${directSeedConversationId}`,
      groupCount: 2,
      actors: [runnerMessageSnapshot],
      latestActorId: "demo-runner",
      entityType: "conversation",
      entityId: directSeedConversationId,
      data: {conversationId: directSeedConversationId, messageId: "seed-message-2"},
      readAt: null,
      deletedAt: null,
      createdAt,
      latestAt: createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "users/demo-athlete/notifications/seed-challenge-activity",
    data: {
      id: "seed-challenge-activity",
      recipientId: "demo-athlete",
      category: "challenges",
      kind: "challenge_reward",
      title: "Reward unlocked",
      body: "Your verified challenge reward is now available.",
      route: "/discover/challenges/rewards",
      groupKey: "challenge_rewards",
      groupCount: 1,
      actors: [],
      latestActorId: null,
      entityType: "challenge",
      entityId: "weekly-running-10k",
      data: {challengeId: "weekly-running-10k"},
      readAt: createdAt,
      deletedAt: null,
      createdAt,
      latestAt: createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "users/demo-athlete/private/notification_summary",
    data: {
      uid: "demo-athlete",
      unreadCount: 2,
      latestAt: createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "notification_deliveries/seed-message-delivery",
    data: {
      eventId: "seed-message-event",
      notificationId: "seed-message-activity",
      recipientId: "demo-athlete",
      type: "conversation_message",
      category: "messages",
      route: `/messages/${directSeedConversationId}`,
      status: "sent",
      tokenCount: 1,
      successCount: 1,
      failureCount: 0,
      createdAt,
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: "trainer_metrics/demo-athlete",
    data: {
      uid: "demo-athlete",
      role: "trainer",
      activeClients: 12,
      sessionsThisMonth: 28,
      retentionRate: 0.82,
      averageRating: 4.7,
      revenueTrend: "stable",
      topSports: ["gym", "running"],
      updatedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
  {
    path: `data_migrations/${seedDatasetVersion}`,
    data: {
      version: seedDatasetVersion,
      type: "seed",
      status: "applied",
      appliedAt: createdAt,
      schemaVersion: currentSchemaVersion,
    },
  },
] as const;
