export const currentSchemaVersion = 1;
export const seedDatasetVersion = "2026-07-14.phase11.v1";

export const collections = {
  users: "users",
  usernames: "usernames",
  sports: "sports",
  places: "places",
  events: "events",
  nearbyEntities: "nearby_entities",
  sportsRoutes: "sports_routes",
  teams: "teams",
  activities: "activities",
  leaderboards: "leaderboards",
  trainerProfiles: "trainer_profiles",
  trainerServices: "trainer_services",
  challenges: "challenges",
  challengeBadges: "challenge_badges",
  challengeRewards: "challenge_rewards",
  rewardClaims: "reward_claims",
  marketplaceListings: "marketplace_listings",
  posts: "posts",
  stories: "stories",
  feedEntries: "feed_entries",
  contentReactions: "content_reactions",
  reposts: "reposts",
  commentReactions: "comment_reactions",
  storyViews: "story_views",
  postViews: "post_views",
  mediaAssets: "media_assets",
  mediaJobs: "media_jobs",
  appConfig: "app_config",
  featureFlags: "feature_flags",
  dataMigrations: "data_migrations",
  accountDeletions: "account_deletions",
  auditLogs: "audit_logs",
  rateLimits: "rate_limits",
  followRequests: "follow_requests",
  verificationRequests: "verification_requests",
  conversations: "conversations",
  messageReports: "message_reports",
  notificationDeliveries: "notification_deliveries",
} as const;
